name: function_macros

sdkPath: .fvm/flutter_sdk

command:
  bootstrap:
    environment:
      sdk: ^3.5.0-323.1.beta
      flutter: ^3.24.0-0.1.pre
    dependencies:
      flutter:
        sdk: flutter
      macros: ^0.1.2-main.4
    dev_dependencies:
      _fe_analyzer_shared: ^73.0.0
      analyzer: ^6.8.0
      flutter_test:
        sdk: flutter
      test: ^1.25.8

packages:
  - packages/**

scripts:
  test:
    exec: dart --enable-experiment=macros test
    packageFilters:
      dependsOn: test
      dirExists: test

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
