name: function_macros
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.0-323.1.beta

dependencies:
  macros: ^0.1.2-main.4

dev_dependencies:
  _fe_analyzer_shared: ^73.0.0
  analyzer: ^6.8.0
  test: ^1.25.8

dependency_overrides:
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_fe_analyzer_shared
      ref: main
  analyzer:
    git:
      url: https://github.com/dart-lang/sdk
      path: pkg/analyzer
      ref: main
  macros:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/macros
      ref: main
