name: app
description: "A sample application of function_macros"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-323.1.beta
  flutter: ^3.24.0-0.1.pre

dependencies:
  flutter:
    sdk: flutter
  function_macros:
    path: ../../packages/function_macros

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
