name: app
description: "A sample application of function_macros"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-323.1.beta

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
